FROM oven/bun:canary-alpine As deps
RUN apk update
WORKDIR /usr/src/app
COPY --chown=node:node package*.json bun.lockb ./
RUN bun install --frozen-lockfile --production
COPY --chown=node:node . .
USER node

###################
# BUILD FOR PRODUCTION
###################

FROM oven/bun:canary-alpine As build
WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./
COPY --chown=node:node --from=deps /usr/src/app/node_modules ./node_modules
COPY --chown=node:node . .
RUN bun install -g @nestjs/cli
RUN bun run build
USER node


###################
# PRODUCTION
###################

FROM oven/bun:canary-alpine As production
RUN apk update && \
apk add --no-cache postgresql-client bash openssl libgcc libstdc++ ncurses-libs tzdata
WORKDIR /usr/src/app

# Copy the bundled code from the build stage to the production image
COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
COPY --chown=node:node --from=build /usr/src/app/dist ./dist
COPY --chown=node:node --from=build /usr/src/app/.env ./

# Start the server using the production build
CMD [ "bun", "dist/main.js" ]